apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  annotations:
    rbac.authorization.kubernetes.io/autoupdate: "true"
  labels:
    kubernetes.io/bootstrapping: rbac-defaults
  name: system:kube-controller-manager-ext
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  - namespaces
  - secrets
  - serviceaccounts
  verbs:
  - get
  - create
  - delete
  - watch
  - update
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  annotations:
    rbac.authorization.kubernetes.io/autoupdate: "true"
  labels:
    kubernetes.io/bootstrapping: rbac-defaults
  name: system:kube-controller-manager-ext
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: system:kube-controller-manager-ext
subjects:
- apiGroup: rbac.authorization.k8s.io
  kind: User
  name: system:kube-controller-manager

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  annotations:
    rbac.authorization.kubernetes.io/autoupdate: "true"
  labels:
    kubernetes.io/bootstrapping: rbac-defaults
  name: system:cluster-manager-registration
rules:
- apiGroups:
  - "rbac.authorization.k8s.io"
  resources:
  - clusterroles
  - clusterrolebindings
  - roles
  - rolebindings
  verbs:
  - get
  - create
  - delete
  - update
- apiGroups:
  - "cluster.open-cluster-management.io"
  resources:
  - managedclusters
  - managedclusters/status
  verbs:
  - get  
  - update
  - patch
- apiGroups:
  - "work.open-cluster-management.io"
  resources:
  - manifestworks
  verbs:
  - get  
  - update
- apiGroups:
  - "work.open-cluster-management.io"
  resources:
  - manifestworks/status
  verbs:
  - patch  
  - update
- apiGroups:
  - "certificates.k8s.io"
  resources:
  - certificatesigningrequests
  verbs:
  - create  
  - get    
- apiGroups:
  - "register.open-cluster-management.io"
  resources:
  - managedclusters/clientcertificates
  verbs:
  - renew
- apiGroups:
  - "addon.open-cluster-management.io"
  resources:
  - managedclusteraddons
  verbs:
  - get
- apiGroups:
  - "addon.open-cluster-management.io"
  resources:
  - managedclusteraddons/status
  verbs:
  - patch
  - update
- apiGroups:
  - "coordination.k8s.io"
  resources:
  - leases
  verbs:
  - get
  - update       

  
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  annotations:
    rbac.authorization.kubernetes.io/autoupdate: "true"
  labels:
    kubernetes.io/bootstrapping: rbac-defaults
  name: system:cluster-manager-registration
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: system:cluster-manager-registration
subjects:
- apiGroup: rbac.authorization.k8s.io
  kind: User
  name: system:kube-controller-manager
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  annotations:
    rbac.authorization.kubernetes.io/autoupdate: "true"
  labels:
    kubernetes.io/bootstrapping: rbac-defaults
  name: system:cluster-manager-placement
rules:
- apiGroups:
  - "cluster.open-cluster-management.io"
  resources:
  - placements/status
  verbs:
  - get
  - update
- apiGroups:  
  - "cluster.open-cluster-management.io"
  resources:
  - placementdecisions
  - placementdecisions/status
  verbs:
  - get
  - create
  - update
  - list  
- apiGroups:
  - "cluster.open-cluster-management.io"
  resources:
  - managedclusterset/bind
  verbs:
  - get
  - create
- apiGroups:
  - "cluster.open-cluster-management.io"
  resources:
  - managedclusterset
  - managedclustersets/status
  verbs:
  - get
  - update
- apiGroups:
  - "app.open-cluster-management.io"
  resources:
  - appbundles
  - appbundles/status
  verbs:
  - get
  - list
  - update
- apiGroups:
  - "work.open-cluster-management.io"
  resources:
  - manifestworks
  - manifestworks/status
  verbs:
  - get
  - list
  - update
  - create
  - delete 

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  annotations:
    rbac.authorization.kubernetes.io/autoupdate: "true"
  labels:
    kubernetes.io/bootstrapping: rbac-defaults
  name: system:cluster-manager-placement
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: system:cluster-manager-placement
subjects:
- apiGroup: rbac.authorization.k8s.io
  kind: User
  name: system:kube-controller-manager