apiVersion: v1
kind: Namespace
metadata:
  name: open-cluster-management-hub
---
apiVersion: v1
kind: Namespace
metadata:
  name: open-cluster-management
---
apiVersion: v1
kind: Namespace
metadata:
  name: vks-system