apiVersion: v1
kind: Service
metadata:
  name: flotta-operator-controller-manager
spec:
  type: NodePort
  ports:
  - name: yggd
    nodePort: 31435
    port: 8888
    protocol: TCP
    targetPort: 8888
  selector:
    control-plane: controller-manager

