apiVersion: app.open-cluster-management.io/v1alpha1
kind: AppBundle
metadata:
  name: appbundle1
  labels:
    cluster.open-cluster-management.io/placement: placement1
spec:
  workload:
    manifests:
      - apiVersion: apps/v1
        kind: Deployment
        metadata:
          namespace: default
          name: appbundle1-nginx
          labels:
            app: appbundle1-nginx
        spec:
          replicas: 1
          selector:
            matchLabels:
              app: appbundle1-nginx
          template:
            metadata:
              labels:
                app: appbundle1-nginx
            spec:
              containers:
                - name: nginx
                  image: nginx:1.14.2
                  ports:
                    - containerPort: 80