apiVersion: app.open-cluster-management.io/v1alpha1
kind: AppBundle
metadata:
  name: appbundle2
  labels:
    cluster.open-cluster-management.io/placement: placement1
spec:
  workload:
    manifests: