apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: default
  name: appbundle2-nginx
  labels:
    cluster.open-cluster-management.io/appbundle: appbundle2
    app: appbundle2-nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: appbundle2-nginx
  template:
    metadata:
      labels:
        app: appbundle2-nginx
    spec:
      containers:
        - name: nginx
          image: nginx:1.14.2
          ports:
            - containerPort: 80