apiVersion: work.open-cluster-management.io/v1
kind: ManifestWork
metadata:
  name: manifestwork1
spec:
  workload:
    manifests:
      - apiVersion: v1
        kind: ServiceAccount
        metadata:
          namespace: default
          name: my-sa
      - apiVersion: apps/v1
        kind: Deployment
        metadata:
          namespace: default
          name: manifestwork1-nginx
          labels:
            app: manifestwork1-nginx
        spec:
          replicas: 1
          selector:
            matchLabels:
              app: manifestwork1-nginx
          template:
            metadata:
              labels:
                app: manifestwork1-nginx
            spec:
              serviceAccountName: my-sa
              containers:
                - name: nginx
                  image: nginx:1.14.2
                  ports:
                    - containerPort: 80