apiVersion: cluster.open-cluster-management.io/v1alpha1
kind: Placement
metadata:
  name: placement1
  namespace: default
spec:
  clusterSets:
    - clusterset1
  predicates:
    - requiredClusterSelector:
        labelSelector:
          matchLabels:
            location: edge1
