apiVersion: kind.x-k8s.io/v1alpha4
kind: Cluster
name: {{ .clusterName }}
nodes:
- role: control-plane
  extraPortMappings:
  - containerPort: {{ .clusterPort1 }}
    hostPort: {{ .clusterPort1 }}
    listenAddress: "0.0.0.0" 
    protocol: tcp
  - containerPort: {{ .clusterPort2 }}
    hostPort: {{ .clusterPort2 }}
    listenAddress: "0.0.0.0" 
    protocol: tcp
  - containerPort: {{ .clusterPort3 }}
    hostPort: {{ .clusterPort3 }}
    listenAddress: "0.0.0.0" 
    protocol: tcp
  - containerPort: {{ .clusterPort4 }}
    hostPort: {{ .clusterPort4 }}
    listenAddress: "0.0.0.0" 
    protocol: tcp
  - containerPort: {{ .clusterPort5 }}
    hostPort: {{ .clusterPort5 }}
    listenAddress: "0.0.0.0" 
    protocol: tcp
  - containerPort: {{ .clusterPort6 }}
    hostPort: {{ .clusterPort6 }}
    listenAddress: "0.0.0.0" 
    protocol: tcp          