kind: Service
apiVersion: v1
metadata:
  name: {{ .vksName }}
spec:
  type: NodePort
  selector:
    app: kube-apiserver
  ports:
  - port: {{ .securePort }}
    nodePort: {{ .clusterPort }}
    name: https
    protocol: TCP
